apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/port: "9153"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
        kubernetes.io/name: CoreDNS
      name: kube-dns
      namespace: kube-system
    spec:
      clusterIP: 10.96.0.10
      clusterIPs:
        - 10.96.0.10
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: dns
          port: 53
          protocol: UDP
          targetPort: 53
        - name: dns-tcp
          port: 53
          protocol: TCP
          targetPort: 53
        - name: metrics
          port: 9153
          protocol: TCP
          targetPort: 9153
      selector:
        k8s-app: kube-dns
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        k8s-app: metrics-server
      name: metrics-server
      namespace: kube-system
    spec:
      clusterIP: 10.100.104.181
      clusterIPs:
        - 10.100.104.181
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - appProtocol: https
          name: https
          port: 443
          protocol: TCP
          targetPort: https
      selector:
        k8s-app: metrics-server
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-coredns
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        jobLabel: coredns
        release: monitoring
      name: monitoring-kube-prometheus-coredns
      namespace: kube-system
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-metrics
          port: 9153
          protocol: TCP
          targetPort: 9153
      selector:
        k8s-app: kube-dns
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-kube-controller-manager
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        jobLabel: kube-controller-manager
        release: monitoring
      name: monitoring-kube-prometheus-kube-controller-manager
      namespace: kube-system
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-metrics
          port: 10257
          protocol: TCP
          targetPort: 10257
      selector:
        component: kube-controller-manager
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-kube-etcd
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        jobLabel: kube-etcd
        release: monitoring
      name: monitoring-kube-prometheus-kube-etcd
      namespace: kube-system
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-metrics
          port: 2381
          protocol: TCP
          targetPort: 2381
      selector:
        component: etcd
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-kube-proxy
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        jobLabel: kube-proxy
        release: monitoring
      name: monitoring-kube-prometheus-kube-proxy
      namespace: kube-system
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-metrics
          port: 10249
          protocol: TCP
          targetPort: 10249
      selector:
        k8s-app: kube-proxy
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-kube-scheduler
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        jobLabel: kube-scheduler
        release: monitoring
      name: monitoring-kube-prometheus-kube-scheduler
      namespace: kube-system
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-metrics
          port: 10259
          protocol: TCP
          targetPort: 10259
      selector:
        component: kube-scheduler
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/managed-by: prometheus-operator
        app.kubernetes.io/name: kubelet
        k8s-app: kubelet
      name: monitoring-kube-prometheus-kubelet
      namespace: kube-system
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
        - IPv6
      ipFamilyPolicy: RequireDualStack
      ports:
        - name: https-metrics
          port: 10250
          protocol: TCP
          targetPort: 10250
        - name: http-metrics
          port: 10255
          protocol: TCP
          targetPort: 10255
        - name: cadvisor
          port: 4194
          protocol: TCP
          targetPort: 4194
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata: {}
