# alertmanager-ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`alerts.kwiki.it.com`)
      kind: Rule
      middlewares:
        - name: traefik-dashboard-basicauth
          namespace: traefik
      services:
        - name: alertmanager-operated
          port: 9093
  tls:
    certResolver: le

