apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app: drone-server
      name: droneserver
      namespace: drone
    spec:
      clusterIP: 10.104.157.136
      clusterIPs:
        - 10.104.157.136
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: drone-server
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app: postgres
      name: postgres
      namespace: drone
    spec:
      clusterIP: 10.111.221.242
      clusterIPs:
        - 10.111.221.242
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        app: postgres
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata: {}
