apiVersion: v1
items:
  - apiVersion: v1
    count: 20117
    eventTime: null
    firstTimestamp: "2025-10-24T13:58:35Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:34:32Z"
    message: announcing from node "s231226.wholesaleinternet.net" with protocol "layer2"
    metadata:
      name: traefik.18717209c335be9a
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T18:42:13Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T18:42:13Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f6c5d511cb18
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T18:42:54Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T18:42:54Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f6cf64b5020a
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T18:48:36Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T18:48:37Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f71f39061b14
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 4
    eventTime: null
    firstTimestamp: "2026-02-10T18:49:14Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T18:49:14Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f727dd384932
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 2
    eventTime: null
    firstTimestamp: "2026-02-10T18:54:55Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T18:54:56Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f7777550b028
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T18:55:34Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T18:55:34Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f78058002898
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:01:14Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:01:15Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f7cfb59f5f01
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:01:54Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:01:54Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f7d8d229d9cc
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:07:34Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:07:35Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f8282cdc50c5
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:08:14Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:08:14Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f8314c3b15f6
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:13:55Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:13:56Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f880e386d285
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:14:34Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:14:34Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f889cb7249cf
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:20:26Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:20:27Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f8dbec645423
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 4
    eventTime: null
    firstTimestamp: "2026-02-10T19:21:04Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:21:04Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f8e49f45253a
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 4
    eventTime: null
    firstTimestamp: "2026-02-10T19:26:52Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:26:53Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f935cadfe5dd
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:27:34Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:27:34Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f93f6d96501e
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:33:14Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:33:15Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f98ebc862887
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:33:54Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:33:54Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f997dc74b891
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
  - apiVersion: v1
    count: 3
    eventTime: null
    firstTimestamp: "2026-02-10T19:39:38Z"
    involvedObject:
      apiVersion: v1
      kind: Service
      name: traefik
      namespace: traefik
      resourceVersion: "50472"
      uid: c1e35584-28f0-4e65-8f26-b6819a8fd590
    kind: Event
    lastTimestamp: "2026-02-10T19:39:39Z"
    message: announcing from node "hcp.kwiki.it.com" with protocol "layer2"
    metadata:
      name: traefik.1892f9e824f707bc
      namespace: traefik
    reason: nodeAssigned
    reportingComponent: metallb-speaker
    reportingInstance: ""
    source:
      component: metallb-speaker
    type: Normal
kind: List
metadata: {}
