apiVersion: v1
items:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      annotations: {}
      name: cyberlynx-blog
      namespace: websites
    spec:
      entryPoints:
        - websecure
      routes:
        - kind: Rule
          match: Host(`xn--cyberlnx-ykb.com`) && !PathPrefix(`/admin`)
          middlewares:
            - name: gzip-compress
              namespace: traefik
            - name: hsts
              namespace: websites
          services:
            - name: cyberlynx-blog
              port: 80
      tls:
        certResolver: le
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      annotations: {}
      name: cyberlynx-blog-admin
      namespace: websites
    spec:
      entryPoints:
        - websecure
      routes:
        - kind: Rule
          match: Host(`xn--cyberlnx-ykb.com`) && PathPrefix(`/admin`)
          middlewares:
            - name: gzip-compress
              namespace: traefik
            - name: hsts
              namespace: websites
            - name: admin-rate-limit
              namespace: websites
          services:
            - name: cyberlynx-blog
              port: 80
      tls:
        certResolver: le
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      annotations: {}
      name: cyberlynx-blog-http
      namespace: websites
    spec:
      entryPoints:
        - web
      routes:
        - kind: Rule
          match: Host(`xn--cyberlnx-ykb.com`)
          middlewares:
            - name: https-redirect
            - name: hsts
          services:
            - name: cyberlynx-blog
              port: 80
kind: List
metadata: {}
