apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: cyberlynx-blog
      name: cyberlynx-blog
      namespace: websites
    spec:
      clusterIP: 10.96.149.201
      clusterIPs:
        - 10.96.149.201
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        app.kubernetes.io/name: cyberlynx-blog
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata: {}
