apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kwiki
  namespace: flux-system
spec:
  interval: 10m
  # Disabled for now (repo/app not production-ready). Set to false later to enable.
  suspend: true
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: kwiki
  targetNamespace: default
