apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-ui
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.kwiki.it.com`)
      kind: Rule
      services:
        - name: ww-gitops-weave-gitops
          port: 9001
  tls:
    certResolver: le
