apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-app-platform.yaml
  - argocd-app-infra.yaml
  - flux-kwiki-repo.yaml
  - flux-kwiki-kustomization.yaml
  - weave-gitops-dashboard.yaml
  - flux-ui-ingressroute.yaml
