apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-30T12:43:04Z"
    labels:
      run: check-ip
    name: check-ip-service
    namespace: default
    resourceVersion: "5797573"
    uid: d23a30e2-8c66-48f9-be92-eb45293db031
  spec:
    clusterIP: 10.99.192.183
    clusterIPs:
    - 10.99.192.183
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      run: check-ip
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"drone-server"},"name":"droneserver","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80},{"name":"https","port":443,"protocol":"TCP","targetPort":443}],"selector":{"app":"drone-server"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-24T14:24:26Z"
    labels:
      app: drone-server
    name: droneserver
    namespace: default
    resourceVersion: "72821"
    uid: 4388fecd-6f8d-4c9d-b89f-e9b2fac1463f
  spec:
    clusterIP: 10.98.84.175
    clusterIPs:
    - 10.98.84.175
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: drone-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-12-01T21:39:12Z"
    labels:
      app: hello-node
    name: hello-node
    namespace: default
    resourceVersion: "6121955"
    uid: 79da70a5-58db-4126-8f8f-65c90c232aec
  spec:
    clusterIP: 10.105.120.249
    clusterIPs:
    - 10.105.120.249
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hello-node
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-10-24T00:53:07Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "238"
    uid: 18331296-62ae-4efd-9c8f-4dc20987c2e6
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"whoami-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80}],"selector":{"app":"whoami"}}}
    creationTimestamp: "2025-10-24T10:56:00Z"
    name: whoami-service
    namespace: default
    resourceVersion: "53929"
    uid: c877bf20-71ce-4784-a9d4-dae74df4e0f3
  spec:
    clusterIP: 10.105.125.48
    clusterIPs:
    - 10.105.125.48
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: whoami
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
