apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"traefik.ingress.kubernetes.io/router.entrypoints":"web","traefik.ingress.kubernetes.io/router.middlewares":"drone-https-redirect@kubernetescrd"},"name":"droneserver-http","namespace":"drone"},"spec":{"ingressClassName":"traefik","rules":[{"host":"drone.kwiki.it.com","http":{"paths":[{"backend":{"service":{"name":"droneserver","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.middlewares: drone-https-redirect@kubernetescrd
    creationTimestamp: "2025-10-24T15:45:12Z"
    generation: 1
    name: droneserver-http
    namespace: drone
    resourceVersion: "80308"
    uid: 9dfdeccc-72ef-4489-b789-d3d93844db11
  spec:
    ingressClassName: traefik
    rules:
    - host: drone.kwiki.it.com
      http:
        paths:
        - backend:
            service:
              name: droneserver
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 69.30.233.178
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"traefik.ingress.kubernetes.io/router.entrypoints":"websecure","traefik.ingress.kubernetes.io/router.tls":"true","traefik.ingress.kubernetes.io/router.tls.certresolver":"le"},"name":"droneserver-https","namespace":"drone"},"spec":{"ingressClassName":"traefik","rules":[{"host":"drone.kwiki.it.com","http":{"paths":[{"backend":{"service":{"name":"droneserver","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["drone.kwiki.it.com"]}]}}
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    creationTimestamp: "2025-10-24T15:45:12Z"
    generation: 1
    name: droneserver-https
    namespace: drone
    resourceVersion: "80310"
    uid: e699f190-081e-470c-8625-36e30bea69c7
  spec:
    ingressClassName: traefik
    rules:
    - host: drone.kwiki.it.com
      http:
        paths:
        - backend:
            service:
              name: droneserver
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - drone.kwiki.it.com
  status:
    loadBalancer:
      ingress:
      - ip: 69.30.233.178
kind: List
metadata:
  resourceVersion: ""
