apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"drone-server"},"name":"droneserver","namespace":"drone"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"drone-server"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-24T15:49:06Z"
    labels:
      app: drone-server
    name: droneserver
    namespace: drone
    resourceVersion: "80642"
    uid: 64319afb-030a-4537-aa2b-df70bcb1c8c2
  spec:
    clusterIP: 10.104.157.136
    clusterIPs:
    - 10.104.157.136
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: drone-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"postgres","namespace":"drone"},"spec":{"ports":[{"name":"http","port":5432,"protocol":"TCP","targetPort":5432}],"selector":{"app":"postgres"}}}
    creationTimestamp: "2025-10-24T14:26:18Z"
    labels:
      app: postgres
    name: postgres
    namespace: drone
    resourceVersion: "73008"
    uid: f33c10be-c52e-4c52-b01b-2909c05eabbb
  spec:
    clusterIP: 10.111.221.242
    clusterIPs:
    - 10.111.221.242
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
