apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.kwiki.it.com`)
      kind: Rule
      services:
        # Verify service name with:
        # kubectl -n flux-system get svc
        - name: ww-gitops-weave-gitops
          port: 9001
  tls:
    certResolver: le
