apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: traefik-dashboard-basicauth@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: le
      labels:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.3.0
        helm.sh/chart: grafana-10.1.5
      name: monitoring-grafana
      namespace: monitoring
    spec:
      ingressClassName: traefik
      rules:
        - host: grafana.kwiki.it.com
          http:
            paths:
              - backend:
                  service:
                    name: monitoring-grafana
                    port:
                      number: 80
                path: /
                pathType: Prefix
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: traefik-dashboard-basicauth@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: le
      labels:
        app: kube-prometheus-stack-prometheus
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        release: monitoring
      name: monitoring-kube-prometheus-prometheus
      namespace: monitoring
    spec:
      ingressClassName: traefik
      rules:
        - host: prometheus.kwiki.it.com
          http:
            paths:
              - backend:
                  service:
                    name: monitoring-kube-prometheus-prometheus
                    port:
                      number: 9090
                path: /
                pathType: Prefix
kind: List
metadata: {}
