apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/managed-by: prometheus-operator
        managed-by: prometheus-operator
        operated-alertmanager: "true"
      name: alertmanager-operated
      namespace: monitoring
      ownerReferences:
        - apiVersion: monitoring.coreos.com/v1
          kind: Alertmanager
          name: monitoring-kube-prometheus-alertmanager
          uid: 56e0a879-e38a-4b61-88ef-52a0181a7209
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-web
          port: 9093
          protocol: TCP
          targetPort: http-web
        - name: tcp-mesh
          port: 9094
          protocol: TCP
          targetPort: mesh-tcp
        - name: udp-mesh
          port: 9094
          protocol: UDP
          targetPort: mesh-udp
      publishNotReadyAddresses: true
      selector:
        app.kubernetes.io/name: alertmanager
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.3.0
        helm.sh/chart: grafana-10.1.5
      name: monitoring-grafana
      namespace: monitoring
    spec:
      clusterIP: 10.104.12.66
      clusterIPs:
        - 10.104.12.66
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-web
          port: 80
          protocol: TCP
          targetPort: grafana
      selector:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/name: grafana
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        release: monitoring
        self-monitor: "true"
      name: monitoring-kube-prometheus-alertmanager
      namespace: monitoring
    spec:
      clusterIP: 10.103.15.108
      clusterIPs:
        - 10.103.15.108
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-web
          port: 9093
          protocol: TCP
          targetPort: 9093
        - appProtocol: http
          name: reloader-web
          port: 8080
          protocol: TCP
          targetPort: reloader-web
      selector:
        alertmanager: monitoring-kube-prometheus-alertmanager
        app.kubernetes.io/name: alertmanager
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-operator
        app.kubernetes.io/component: prometheus-operator
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        release: monitoring
      name: monitoring-kube-prometheus-operator
      namespace: monitoring
    spec:
      clusterIP: 10.108.145.35
      clusterIPs:
        - 10.108.145.35
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: https
      selector:
        app: kube-prometheus-stack-operator
        release: monitoring
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app: kube-prometheus-stack-prometheus
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 79.6.1
        chart: kube-prometheus-stack-79.6.1
        heritage: Helm
        release: monitoring
        self-monitor: "true"
      name: monitoring-kube-prometheus-prometheus
      namespace: monitoring
    spec:
      clusterIP: 10.97.69.182
      clusterIPs:
        - 10.97.69.182
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-web
          port: 9090
          protocol: TCP
          targetPort: 9090
        - appProtocol: http
          name: reloader-web
          port: 8080
          protocol: TCP
          targetPort: reloader-web
      selector:
        app.kubernetes.io/name: prometheus
        operator.prometheus.io/name: monitoring-kube-prometheus-prometheus
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/part-of: kube-state-metrics
        app.kubernetes.io/version: 2.17.0
        helm.sh/chart: kube-state-metrics-6.4.1
        release: monitoring
      name: monitoring-kube-state-metrics
      namespace: monitoring
    spec:
      clusterIP: 10.109.34.76
      clusterIPs:
        - 10.109.34.76
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: http
      selector:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/name: kube-state-metrics
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prometheus-node-exporter
        app.kubernetes.io/part-of: prometheus-node-exporter
        app.kubernetes.io/version: 1.10.2
        helm.sh/chart: prometheus-node-exporter-4.49.1
        jobLabel: node-exporter
        release: monitoring
      name: monitoring-prometheus-node-exporter
      namespace: monitoring
    spec:
      clusterIP: 10.107.63.237
      clusterIPs:
        - 10.107.63.237
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-metrics
          port: 9100
          protocol: TCP
          targetPort: 9100
      selector:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/name: prometheus-node-exporter
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/managed-by: prometheus-operator
        managed-by: prometheus-operator
        operated-prometheus: "true"
      name: prometheus-operated
      namespace: monitoring
      ownerReferences:
        - apiVersion: monitoring.coreos.com/v1
          kind: Prometheus
          name: monitoring-kube-prometheus-prometheus
          uid: d52be81e-22a1-483b-861a-2ca76ba85f38
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http-web
          port: 9090
          protocol: TCP
          targetPort: http-web
      selector:
        app.kubernetes.io/name: prometheus
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata: {}
