apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        run: check-ip
      name: check-ip-service
      namespace: default
    spec:
      clusterIP: 10.99.192.183
      clusterIPs:
        - 10.99.192.183
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - port: 80
          protocol: TCP
          targetPort: 80
      selector:
        run: check-ip
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app: drone-server
      name: droneserver
      namespace: default
    spec:
      clusterIP: 10.98.84.175
      clusterIPs:
        - 10.98.84.175
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
      selector:
        app: drone-server
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hello-node
      name: hello-node
      namespace: default
    spec:
      clusterIP: 10.105.120.249
      clusterIPs:
        - 10.105.120.249
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: hello-node
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        component: apiserver
        provider: kubernetes
      name: kubernetes
      namespace: default
    spec:
      clusterIP: 10.96.0.1
      clusterIPs:
        - 10.96.0.1
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 6443
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      name: whoami-service
      namespace: default
    spec:
      clusterIP: 10.105.125.48
      clusterIPs:
        - 10.105.125.48
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: whoami
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata: {}
