apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"cyberlynx-blog"},"name":"cyberlynx-blog","namespace":"websites"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8080}],"selector":{"app.kubernetes.io/name":"cyberlynx-blog"},"type":"ClusterIP"}}
    creationTimestamp: "2026-02-08T14:00:24Z"
    labels:
      app.kubernetes.io/name: cyberlynx-blog
    name: cyberlynx-blog
    namespace: websites
    resourceVersion: "22601541"
    uid: aa6aa800-ab4f-4159-a26d-f71c857670fe
  spec:
    clusterIP: 10.96.149.201
    clusterIPs:
    - 10.96.149.201
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/name: cyberlynx-blog
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
