apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: backup
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.kwiki.it.com`)
      kind: Rule
      services:
        - name: minio
          port: 9001
  tls:
    certResolver: le
