apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-20T10:15:48Z"
    name: default
    namespace: grafana
    resourceVersion: "3364326"
    uid: dbde1eea-07df-41ed-b834-04ad3795ac77
kind: List
metadata:
  resourceVersion: ""
