apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd-tcp
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`argo.kwiki.it.com`)
      services:
        - name: argocd-server
          port: 443
  tls:
    passthrough: true
