apiVersion: v1
items:
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"traefik-dashboard-web","namespace":"traefik"},"spec":{"entryPoints":["web"],"routes":[{"kind":"Rule","match":"Host(`traefik.kwiki.it.com`)","middlewares":[{"name":"https-redirect"}],"services":[{"kind":"TraefikService","name":"api@internal"}]}]}}
    creationTimestamp: "2025-10-24T10:44:10Z"
    generation: 1
    name: traefik-dashboard-web
    namespace: traefik
    resourceVersion: "52901"
    uid: 3d3f3491-2f35-46d2-a469-5b9e3fb70611
  spec:
    entryPoints:
    - web
    routes:
    - kind: Rule
      match: Host(`traefik.kwiki.it.com`)
      middlewares:
      - name: https-redirect
      services:
      - kind: TraefikService
        name: api@internal
- apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"IngressRoute","metadata":{"annotations":{},"name":"traefik-dashboard-websecure","namespace":"traefik"},"spec":{"entryPoints":["websecure"],"routes":[{"kind":"Rule","match":"Host(`traefik.kwiki.it.com`)","middlewares":[{"name":"dashboard-basicauth"}],"services":[{"kind":"TraefikService","name":"api@internal"}]}],"tls":{"certResolver":"le"}}}
    creationTimestamp: "2025-10-24T10:44:10Z"
    generation: 1
    name: traefik-dashboard-websecure
    namespace: traefik
    resourceVersion: "52900"
    uid: 10aae948-e1aa-431a-bd28-1a3a6f5d9753
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`traefik.kwiki.it.com`)
      middlewares:
      - name: dashboard-basicauth
      services:
      - kind: TraefikService
        name: api@internal
    tls:
      certResolver: le
kind: List
metadata:
  resourceVersion: ""
