apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"acme-pvc","namespace":"traefik"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"256Mi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2025-10-24T11:16:17Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: acme-pvc
    namespace: traefik
    resourceVersion: "55789"
    uid: 3c05231e-5365-4361-aa7f-b56925391e53
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 256Mi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: traefik-pv
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
