apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-10-24T10:16:46Z"
    name: default
    namespace: traefik
    resourceVersion: "50460"
    uid: 8cf02dc2-c055-4761-a1d6-e711d4479cec
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: traefik
      meta.helm.sh/release-namespace: traefik
    creationTimestamp: "2025-10-24T10:16:47Z"
    labels:
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
      helm.sh/chart: traefik-37.2.0
    name: traefik
    namespace: traefik
    resourceVersion: "50462"
    uid: 932f6f66-7f02-48dc-84a9-a303992606c7
kind: List
metadata:
  resourceVersion: ""
